# sheldon configuration file
#
# See https://github.com/rossmacarthur/sheldon

# By default plugin sourcing is deferred
apply = ["defer"]

[templates]
defer = { value = 'zsh-defer source "{{ file }}"', each = true }

# Sourced
# -------

[plugins.pure]
github = "rossmacarthur/pure"
use = ["async.zsh", "pure.zsh"]
apply = ["source"]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

# fpath only
# ----------
[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
dir = "src"
apply = ["fpath"]

# Deferred
# --------

[plugins.autoenv]
github = "zpm-zsh/autoenv"

[plugins.dotfiles]
local = "~/.zsh/plugins"

[plugins.syntax-highlighting]
github = 'zdharma/fast-syntax-highlighting'

[plugins.wd]
github = "mfaerevaag/wd"
apply = ["fpath", "defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.zsh-you-should-use]
github = "MichaelAquilina/zsh-you-should-use"

# Things just work best if this is sourced last.
[plugins.ohmyzsh]
github = "ohmyzsh/ohmyzsh"
