# sheldon configuration file
#
# See https://github.com/rossmacarthur/sheldon

[plugins.autoenv]
github = "zpm-zsh/autoenv"

[plugins.dotfiles]
local = "~/.zsh/plugins"

[plugins.pure]
github = "rossmacarthur/pure"
use = ["async.zsh", "pure.zsh"]

[plugins.syntax-highlighting]
github = 'zdharma/fast-syntax-highlighting'

[plugins.wd]
github = "mfaerevaag/wd"
apply = ["fpath", "source"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
dir = "src"
apply = ["fpath"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.zsh-you-should-use]
github = "MichaelAquilina/zsh-you-should-use"

# Things just work best if this is sourced last.
[plugins.ohmyzsh]
github = "ohmyzsh/ohmyzsh"
