# sheldon configuration file
#
# See https://github.com/rossmacarthur/sheldon

# By default plugin sourcing is deferred
apply = ["defer"]

[templates]
defer = { value = 'zsh-defer source "{{ file }}"', each = true }
defer-more = { value = 'zsh-defer -t 0.5 source "{{ file }}"', each = true }

# fpath only
# ----------
[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
dir = "src"
apply = ["fpath"]

# Sourced
# -------

# The history plugin doesn't like being deferred, not sure why.
[plugins.history]
github = "ohmyzsh/ohmyzsh"
dir = "lib"
apply = ["source"]

[plugins.pure]
github = "rossmacarthur/pure"
use = ["async.zsh", "pure.zsh"]
apply = ["source"]

[plugins.wd]
github = "mfaerevaag/wd"
apply = ["fpath", "source"]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

# Deferred
# --------

[plugins.autoenv]
github = "zpm-zsh/autoenv"

[plugins.dotfiles]
local = "~/.zsh/plugins"
use = ["{!compinit,!pyenv,*}.plugin.zsh"]

[plugins.ohmyzsh-lib]
github = "ohmyzsh/ohmyzsh"
dir = "lib"
use = ["{clipboard,completion,git,key-bindings,termsupport,theme-and-appearance}.zsh"]

[plugins.ohmyzsh-plugins]
github = "ohmyzsh/ohmyzsh"
dir = "plugins"
use = ["{copybuffer,git,pip}/*.plugin.zsh"]
apply = ["fpath", "defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'

[plugins.compinit]
local = "~/.zsh/plugins"

# Deferred even more
# ------------------

[plugins.pyenv]
local = "~/.zsh/plugins"
apply = ["defer-more"]
