# sheldon configuration file
#
# See https://github.com/rossmacarthur/sheldon

[plugins.autoenv]
github = "zpm-zsh/autoenv"

[plugins.dotfiles]
local = "~/.zsh/plugins"

[plugins.pure]
github = "rossmacarthur/pure"
use = ["async.zsh", "pure.zsh"]

[plugins.wd]
github = "mfaerevaag/wd"
apply = ["fpath", "source"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

# Things just work best if this is sourced last.
[plugins.ohmyzsh]
github = "ohmyzsh/ohmyzsh"
