# sheldon configuration file
#
# See https://github.com/rossmacarthur/sheldon

[templates]
alias = { value = '{{ name }}() { source {{ filename }} }', each = true }
function = { value = 'ln -sf "{{ filename }}" "{{ root }}/functions/{{ name }}"', each = true }
prompt = { value = 'ln -sf "{{ filename }}" "{{ root }}/functions/prompt_{{ name }}_setup"', each = true }

[plugins.async]
github = "mafredri/zsh-async"
apply = ["function"]
use = ["{{ name }}.zsh"]

[plugins.pure]
github = "rossmacarthur/pure"
apply = ["prompt"]

[plugins.autoenv]
github = "zpm-zsh/autoenv"
branch = "master"

[plugins.copybuffer]
github = "robbyrussell/oh-my-zsh"
directory = "plugins/{{ name }}"

[plugins.docker]
remote = "https://raw.githubusercontent.com/docker/cli/master/contrib/completion/zsh/_docker"
apply = ["fpath"]

[plugins.docker-compose]
remote = "https://raw.githubusercontent.com/docker/compose/master/contrib/completion/zsh/_docker-compose"
apply = ["fpath"]

[plugins.dotfiles]
local = "~/.zsh/plugins"

[plugins.oh-my-zsh]
github = "robbyrussell/oh-my-zsh"
directory = "lib"
use = ["completion.zsh", "key-bindings.zsh", "git.zsh", "history.zsh"]

[plugins.pip]
github = "robbyrussell/oh-my-zsh"
directory = "plugins/{{ name }}"
apply = ["fpath"]

[plugins.wd]
github = "mfaerevaag/wd"
tag = "v0.4.6"
apply = ["alias", "fpath"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
tag = "v0.5.2"
use = ["{{ name }}.zsh"]

# The `git` plugin requires `compinit` to have been called before being sourced.
[plugins.compinit]
inline = "compinit"

[plugins.git]
github = "robbyrussell/oh-my-zsh"
directory = "plugins/{{ name }}"
